"""Amazon Bedrock list prices, from AWS's own public price list.

GENERATED by scripts/refresh_bedrock_prices.py — do not edit by hand.

Region us-east-1, on-demand, USD per million tokens. Bedrock resells other
vendors' models, so these are what AWS charges for them, not what those
vendors charge on their own APIs — the two differ, sometimes a lot.

Shown as reference rather than used for costing: the price list identifies
models by display name ("Llama 3.3 70B"), and Meter costs traffic by the API
model id ("meta.llama3-3-70b-instruct-v1:0"). Mapping one to the other is not
derivable from this source, and guessing it would mis-cost real bills.
"""

from __future__ import annotations

PUBLISHED = "2026-09-26"

#: (vendor, model) -> per-million rates. A key is ABSENT where AWS
#: publishes no such rate — notably there is no output price for the
#: older Anthropic models, and most vendors have no batch tier.
CATALOG: dict = {
    ("Amazon", "Nova 2.0 Lite"): {"in": "0.3", "out": "1.25", "cache_read": "0.0825"},
    ("Amazon", "Nova Lite"): {"in": "0.06", "out": "0.24", "cache_read": "0.015"},
    ("Amazon", "Nova Micro"): {"in": "0.0175", "out": "0.14", "cache_read": "0.00875"},
    ("Amazon", "Nova Premier"): {"in": "1.25", "out": "12.5", "cache_read": "0.625"},
    ("Amazon", "Nova Pro"): {"in": "0.8", "out": "3.2", "cache_read": "0.2"},
    ("Amazon", "Nova Pro Latency Optimized"): {"in": "1", "out": "4"},
    ("Anthropic", "Claude 2.0"): {"in": "8"},
    ("Anthropic", "Claude 2.1"): {"in": "8"},
    ("Anthropic", "Claude 3 Haiku"): {"in": "0.25"},
    ("Anthropic", "Claude 3 Sonnet"): {"in": "3"},
    ("Anthropic", "Claude Instant"): {"in": "0.8"},
    ("DeepSeek", "DeepSeek V3.1"): {
        "in": "0.58", "out": "1.68", "in_batch": "0.29", "out_batch": "0.84",
    },
    ("DeepSeek", "DeepSeek v3.2"): {
        "in": "0.62", "out": "1.85", "in_batch": "0.31", "out_batch": "0.925",
    },
    ("DeepSeek", "R1"): {"in": "1.35", "out": "5.4"},
    ("Google", "Gemma 3 12B"): {
        "in": "0.09", "out": "0.15", "in_batch": "0.05", "out_batch": "0.15",
    },
    ("Google", "Gemma 3 27B"): {
        "in": "0.23", "out": "0.38", "in_batch": "0.12", "out_batch": "0.19",
    },
    ("Google", "Gemma 3 4B"): {
        "in": "0.02", "out": "0.04", "in_batch": "0.02", "out_batch": "0.04",
    },
    ("Google", "google.gemma-4-26b-a4b"): {
        "in": "0.13", "out": "0.4", "in_batch": "0.065", "out_batch": "0.2",
    },
    ("Google", "google.gemma-4-31b"): {
        "in": "0.14", "out": "0.4", "in_batch": "0.07", "out_batch": "0.2",
    },
    ("Google", "google.gemma-4-e2b"): {
        "in": "0.04", "out": "0.08", "in_batch": "0.02", "out_batch": "0.04",
    },
    ("Meta", "Llama 3 70B"): {"in": "2.65", "out": "3.5"},
    ("Meta", "Llama 3 8B"): {"in": "0.3", "out": "0.6"},
    ("Meta", "Llama 3.1 405B"): {"in": "1.2", "out": "1.2"},
    ("Meta", "Llama 3.1 70B"): {"in": "0.72", "out": "0.72"},
    ("Meta", "Llama 3.1 70B Latency Optimized"): {"in": "0.9", "out": "0.9"},
    ("Meta", "Llama 3.1 8B"): {"in": "0.22", "out": "0.22"},
    ("Meta", "Llama 3.2 11B"): {"in": "0.16", "out": "0.16"},
    ("Meta", "Llama 3.2 1B"): {"in": "0.1", "out": "0.1"},
    ("Meta", "Llama 3.2 3B"): {"in": "0.15", "out": "0.15"},
    ("Meta", "Llama 3.2 90B"): {"in": "0.72", "out": "0.72"},
    ("Meta", "Llama 3.3 70B"): {"in": "0.36", "out": "0.36"},
    ("Meta", "Llama 4 Maverick 17B"): {"in": "0.12", "out": "0.97"},
    ("Meta", "Llama 4 Scout 17B"): {"in": "0.17", "out": "0.33"},
    ("Minimax AI", "Minimax M2"): {
        "in": "0.3", "out": "0.6", "in_batch": "0.15", "out_batch": "0.6",
    },
    ("Minimax AI", "Minimax M2.1"): {
        "in": "0.3", "out": "1.2", "in_batch": "0.15", "out_batch": "0.6",
    },
    ("Minimax AI", "MiniMax M2.5"): {
        "in": "0.3", "out": "1.2", "in_batch": "0.15", "out_batch": "0.6",
    },
    ("Mistral", "Devstral"): {"in": "0.4", "out": "2", "in_batch": "0.2", "out_batch": "1"},
    ("Mistral", "Magistral Small 1.2"): {
        "in": "0.5", "out": "1.5", "in_batch": "0.25", "out_batch": "0.75",
    },
    ("Mistral", "Ministral 14B 3.0"): {
        "in": "0.2", "out": "0.2", "in_batch": "0.1", "out_batch": "0.1",
    },
    ("Mistral", "Ministral 3B 3.0"): {
        "in": "0.1", "out": "0.1", "in_batch": "0.05", "out_batch": "0.05",
    },
    ("Mistral", "Ministral 8B 3.0"): {
        "in": "0.15", "out": "0.15", "in_batch": "0.07", "out_batch": "0.07",
    },
    ("Mistral", "Mistral 7B"): {"in": "0.15", "out": "0.2"},
    ("Mistral", "Mistral Large"): {"in": "4", "out": "12"},
    ("Mistral", "Mistral Large 3"): {
        "in": "0.5", "out": "1.5", "in_batch": "0.25", "out_batch": "0.75",
    },
    ("Mistral", "Mistral Small"): {"in": "1", "out": "3"},
    ("Mistral", "Mixtral 8x7B"): {"in": "0.45", "out": "0.7"},
    ("Mistral", "Pixtral Large 25.02"): {"in": "2", "out": "6"},
    ("Mistral", "Voxtral Mini 1.0"): {
        "in": "0.04", "out": "0.04", "in_batch": "0.02", "out_batch": "0.02",
    },
    ("Mistral", "Voxtral Small 1.0"): {
        "in": "0.05", "out": "0.3", "in_batch": "0.05", "out_batch": "0.15",
    },
    ("Moonshot AI", "Kimi K2 Thinking"): {
        "in": "0.6", "out": "2.5", "in_batch": "0.3", "out_batch": "1.25",
    },
    ("Moonshot AI", "Kimi K2.5"): {"in": "0.6", "out": "3", "in_batch": "0.3", "out_batch": "1.5"},
    ("Moonshot AI", "Kimi K3"): {
        "in": "3.3", "out": "16.5", "in_batch": "1.65", "out_batch": "8.25",
    },
    ("Nvidia", "Nemotron Nano 3 30B"): {
        "in": "0.06", "out": "0.24", "in_batch": "0.03", "out_batch": "0.12",
    },
    ("Nvidia", "NVIDIA Nemotron 3 Super 120B A12B"): {
        "in": "0.15", "out": "0.65", "in_batch": "0.075", "out_batch": "0.325",
    },
    ("Nvidia", "NVIDIA Nemotron Nano 2"): {
        "in": "0.03", "out": "0.23", "in_batch": "0.03", "out_batch": "0.12",
    },
    ("Nvidia", "NVIDIA Nemotron Nano 2 VL"): {
        "in": "0.2", "out": "0.6", "in_batch": "0.1", "out_batch": "0.3",
    },
    ("OpenAI", "GPT OSS Safeguard 120B"): {
        "in": "0.15", "out": "0.6", "in_batch": "0.07", "out_batch": "0.3",
    },
    ("OpenAI", "GPT OSS Safeguard 20B"): {
        "in": "0.07", "out": "0.2", "in_batch": "0.03", "out_batch": "0.1",
    },
    ("OpenAI", "gpt-oss-120b"): {
        "in": "0.15", "out": "0.3", "in_batch": "0.075", "out_batch": "0.3",
    },
    ("OpenAI", "gpt-oss-20b"): {
        "in": "0.035", "out": "0.3", "in_batch": "0.035", "out_batch": "0.15",
    },
    ("Qwen", "Qwen3 235B A22B 2507"): {
        "in": "0.22", "out": "0.88", "in_batch": "0.11", "out_batch": "0.44",
    },
    ("Qwen", "Qwen3 32B"): {"in": "0.15", "out": "0.6", "in_batch": "0.075", "out_batch": "0.3"},
    ("Qwen", "Qwen3 Coder 30B A3B"): {
        "in": "0.15", "out": "0.6", "in_batch": "0.075", "out_batch": "0.3",
    },
    ("Qwen", "Qwen3 Coder 480B A35B"): {
        "in": "0.45", "out": "1.8", "in_batch": "0.225", "out_batch": "0.9",
    },
    ("Qwen", "Qwen3 Coder Next"): {
        "in": "0.5", "out": "1.2", "in_batch": "0.25", "out_batch": "0.6",
    },
    ("Qwen", "Qwen3 Next 80B A3B"): {
        "in": "0.14", "out": "1.2", "in_batch": "0.07", "out_batch": "0.6",
    },
    ("Qwen", "Qwen3 VL 235B A22B"): {
        "in": "0.26", "out": "1.33", "in_batch": "0.26", "out_batch": "1.33",
    },
    ("Writer", "Writer Palmyra Vision 7B"): {
        "in": "0.15", "out": "0.6", "in_batch": "0.075", "out_batch": "0.3",
    },
    ("Z AI", "GLM 4.7"): {"in": "0.6", "out": "2.2", "in_batch": "0.3", "out_batch": "1.1"},
    ("Z AI", "GLM 4.7 Flash"): {
        "in": "0.07", "out": "0.4", "in_batch": "0.035", "out_batch": "0.2",
    },
    ("Z AI", "GLM 5"): {"in": "1", "out": "3.2", "in_batch": "0.5", "out_batch": "1.6"},
}
