#!/usr/bin/env python3
"""Regenerate backend/meter/bedrock_prices.py from AWS's own public price list.

Bedrock resells a dozen other vendors' models, and its pricing page is a tab per
vendor with no stable machine-readable export behind it. Summarising that page
gets you a plausible subset and no way to tell which rows are missing — so this
reads the price list API instead, which is the same data AWS bills from:

    https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonBedrock/...

Generated rather than hand-maintained because 70-odd models across 15 vendors is
more than anyone will keep current by hand, and a stale price book is worse than
an obviously absent one. Re-run it and commit the result.

    python3 scripts/refresh_bedrock_prices.py

us-east-1 and on-demand: Bedrock prices vary by region, and every other rate in
this product is a standard-tier list price, so this matches. The page says so.
"""

from __future__ import annotations

import collections
import json
import pathlib
import urllib.request

INDEX = "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonBedrock/current/region_index.json"
REGION = "us-east-1"
OUT = pathlib.Path(__file__).resolve().parent.parent / "backend" / "meter" / "bedrock_prices.py"

#: The token kinds worth showing. Bedrock also prices provisioned throughput,
#: customization, priority and flex tiers; none is a per-token list rate and
#: none belongs beside the other providers on that screen.
KINDS = {
    "Input tokens": "in",
    "Output tokens": "out",
    "input tokens batch": "in_batch",
    "output tokens batch": "out_batch",
    "Prompt cache read input tokens": "cache_read",
}

#: AWS labels the same vendor two ways in places, and leaves Amazon's own models
#: with no provider at all.
VENDOR = {None: "Amazon", "Mistral AI": "Mistral", "Kimi AI": "Moonshot AI"}


def _fetch(url: str) -> dict:
    with urllib.request.urlopen(url, timeout=120) as resp:  # noqa: S310 (fixed https host)
        return json.load(resp)


def _rate(terms: dict, sku: str):
    for term in terms.get(sku, {}).values():
        for dim in term["priceDimensions"].values():
            return float(dim["pricePerUnit"]["USD"])
    return None


def _money(value) -> str:
    """A price as a plain decimal string, without float noise.

    The price list gives 0.00072 per 1K, which becomes 0.7200000000000001 per
    million if you let it. Every other rate in this book is a string for the
    same reason.
    """
    if value is None:
        return "None"
    return '"%s"' % format(round(value, 6), "f").rstrip("0").rstrip(".")


def main() -> None:
    region = _fetch(INDEX)["regions"][REGION]
    data = _fetch("https://pricing.us-east-1.amazonaws.com" + region["currentVersionUrl"])
    terms = data["terms"]["OnDemand"]

    rows: dict = collections.defaultdict(dict)
    for sku, product in data["products"].items():
        attrs = product["attributes"]
        kind = KINDS.get(attrs.get("inferenceType"))
        model = attrs.get("model")
        if not kind or not model:
            continue
        rate = _rate(terms, sku)
        if rate:  # a zero is "not offered", not "free"
            vendor = attrs.get("provider")
            rows[(VENDOR.get(vendor, vendor), model)][kind] = rate * 1000

    lines = [
        '"""Amazon Bedrock list prices, from AWS\'s own public price list.',
        "",
        "GENERATED by scripts/refresh_bedrock_prices.py — do not edit by hand.",
        "",
        f"Region {REGION}, on-demand, USD per million tokens. Bedrock resells other",
        "vendors' models, so these are what AWS charges for them, not what those",
        "vendors charge on their own APIs — the two differ, sometimes a lot.",
        "",
        "Shown as reference rather than used for costing: the price list identifies",
        'models by display name ("Llama 3.3 70B"), and Meter costs traffic by the API',
        'model id ("meta.llama3-3-70b-instruct-v1:0"). Mapping one to the other is not',
        "derivable from this source, and guessing it would mis-cost real bills.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        f'PUBLISHED = "{data["publicationDate"][:10]}"',
        "",
        "#: (vendor, model) -> per-million rates. A key is ABSENT where AWS",
        "#: publishes no such rate — notably there is no output price for the",
        "#: older Anthropic models, and most vendors have no batch tier.",
        "CATALOG: dict = {",
    ]
    for (vendor, model), rates in sorted(rows.items(), key=lambda kv: (kv[0][0].lower(), kv[0][1].lower())):
        fields = ", ".join(
            f'"{k}": {_money(rates[k])}'
            for k in ("in", "out", "in_batch", "out_batch", "cache_read")
            if rates.get(k) is not None
        )
        entry = f'    ("{vendor}", "{model}"): {{{fields}}},'
        if len(entry) <= 100:
            lines.append(entry)
        else:  # a few vendor/model names are long enough to need the break
            lines.append(f'    ("{vendor}", "{model}"): {{')
            lines.append(f"        {fields},")
            lines.append("    },")
    lines += ["}", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} — {len(rows)} models, published {data['publicationDate'][:10]}")


if __name__ == "__main__":
    main()
